# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/ruby
assets:
  pwd: yegor256/home#assets/docker-password
install: |
  pdd --file=/dev/null
merge:
  script: |
    sudo make install -f "$(pwd)/Makefile"
    make env lint test
release:
  pre: false
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
    sed -i "s/0\.0\.0/${tag}/g" Makefile
    curl -s -L "https://download.docker.com/linux/static/stable/x86_64/docker-18.06.3-ce.tgz" | tar -xz -C /tmp
    sudo mv /tmp/docker/docker /usr/bin/
    repo=yegor256/cam
    sudo docker build --no-cache --tag "${repo}:${tag}" "$(pwd)"
    mkdir /tmp/dataset
    sudo docker run --rm "${repo}:${tag}" make install env lint test
    cat ../pwd | sudo docker login --password-stdin --username yegor256
    sudo docker push "${repo}:${tag}"
